language: scala

scala:
   - 2.11.8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

script:
  - sbt compile test

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm

jdk:
   - oraclejdk8

notifications:
  email:
    - pedro.diaz@full360.com

env:
  # SONATYPE_USERNAME
  # SONATYPE_PASSWORD
  # SONATYPE_KEY_ID
  # SONATYPE_KEY_PASSPHRASE
  global:
  - secure: i4Dm6dOkl1mHDDNHBOZPAz5wUUJi2TavA90pR8LMgvKXQx1iGbiL3z7R3Pj4RSG4JN+3hk038WJrNDNC8Qoib1Ay0vzjSfmIeJO9Mka1zdsyzymB9WnOi6SjlRayL06REgFX4GH2lPInCe/UiITZh9SggP2Mw6oA3B7deJXSzXZs3KzRfppYJSlRefQoInL7OgRyvdXr/sqS+eZQQHGhx9FpcdEr3jh8w4zldWsWpx4Nj9Pr5N3D+/u/G2du/TvPQnukdirIdMo4fJmC1+DL3B3R07gsukb8WHyuniWoAIxogsSgGpAV98we3nAhpmAgD+PUGwZHRCgJYohnDf43SnJOPjJKfyt4GfpDwWvH5c+pIWBwepxfrPt1s2O0q/qjSGvGlBpbORJeagfqPotkLQZT/4KUI/Qx3ToE8EGAxdX7rtAlMChuPV5U/JpC0Kip8QZQT/CWhmuU9gKXUQAXuCC0cWT9s20SiUh46hDIxKv6yCUDgS6V9AklTh++N8/inrn/sxezxIvKkwFqZ+pAK9NFYH/gMEoLcp8DO2xSLxpqeOwtijwAKThoX419E8ZvzjZ0miEQXL7BhQTiqDI+6s1dsTXyIcssqh2zgcBGKauxxpshd6uORApxX02GhquLXy1kU28hx1ppOv3VolS6kBaj+DWfh6fcizLyEbrOiXM=
  - secure: iCcXnlQdfJbrM2NBinJOaPRl8Xca/dwMRmqBWcbc+Jya19AtIm8fC9DsjKuBYbT7Uwp+6EjdVTCXkG3tfFhDwY0wjrrChrjgrIizRC8oFIfCOMF3nbeeoilKR6aplC/Q7nMF5Imc7pOKlc2OZBTxxVYsqIpsbfgj7rDqWbg7nCddaze6B2qwr4aAYy3vlNL/8smxKeGIKckbFUNNVtONB3n2+VfmcVOmJN7hYHKlGZ/9Jc+m3Ol+AZcyn400keNIKa1zkZMPNYS8pV6hzv4qpXupQNJmLrANAhuK1/NsVdcjheDf70f+JeVgPef/Sk2JSxN1tGQeQXbTaK9qZ3hsiw4X7uQX3koM0CaB/Vh5z1J1QL/KYZfhlNaEciu6Enei0+uJC1+tBsv4ys/si76GE5L2+iSFERE/9mFFt4WnFAC/XC8uFF3MPWk4jfjQ/wdI4G4sBanICbzaL8B23v9uHct8lK7k9YlvgCfXlI9rneZOyIsrZenhPUddSuylUnCrAvwZKa45yzYyYcqEZDUKqW3+VnCjkkvYy3Wc/H1OFcNqXp0Q/GZ4vByFfjxmpNTge1OjFJTInw5Gehe1+642VBsDuFslRy7rs9MdoSheSdSnATrCkkzyQStCI4eyolFJxi+g5Zmo15ILv78nh29+QMhusTTsUkwC82eO27J6mYg=
  - secure: hfhyTDSGaHl0ZK6EALlEOwW2g90cdOyKJPUFkVuy1fW3oE29K7TDEJ28ca0sERzeaJXqC/wZQallcIfwkzSB2+mkJpwieIUNmLcsVdNTQLuA9BeQd2i4ntFpYDMLD/i3MuM505byJWzWAhTA0GCKtJeaE/on3Cf4P9noKArS87sWh92IdqB9xAtu5F63Fuq+G34i8cxmbHAxPkO9lwTzaH/N5/duNtku2tfmFt7dXyWGt11AKYte7cncVT6PAtLwnNUgzQbSvb767rOdqpV+tONIKsEZXO7/Jd9Pm2L07v08IjDHzURAzQYXgQJsrDLRz/T0o06QDJlA0wtw+9Eq+DJU++p+h+0by71812uYmcmj9wG5KBR0MiJ6hmVO1oUpTEw0eNvuUwu/6iuIe7gJ4dG8IeaN3DDadwTfH7EjEv2ktlKGlz8AISHojh3a0NnAuk7Yfh6lEYWMYJfaWtzBjR8MR6vYr1oqVPmOSOzzhzo62XUmtGikrHd6lAISV3b9R/wxdVMbQpBhCKk5lyJuDV8znlKEJj8Bs0qAB+SrwkFSbIDzbcjqHr9V+u2vqXc/fvbirtL8leHXhnYvRFvLPtlXf4Li7FnzW3MTqHMr6r10QT/piPe7ldQarW1l2R1Izf9dVe6wmKkDEu/6ILp3PJdI8n5thEb4ui7a4NvcPCg=
  - secure: QFXccSNimKgU7+0wF/Yt0Pdf0IsWLHJ+9dhMdxoKyovRnTXsWzY+G8DwAZ6U1LU6/SK8V7Kdk/Pw6XEaoOtXWn87kKYtr05LsmZjfHc0cBpKx2WTwu1N9uWa2+n8jesjtfw46HWkbAbJAqQ7NVZtzXEYaCAUWri/Bjy7dm95q9Xa2fvDmad0aHabEqDgbOfEwDiLCcXaO0pJ/ULke8xQB5L6XQj3e4KFBXOBqW8Jn+jU3lgHvomO/liMMKVAv1k7s5YZwccbaSqbEnRT3Kq6mVIbN46aPKysbDjwC+6HT+ReJgymbwFVSdipREasYEsAMqNzktDmq0RmTbeBoid7xP8qWbGjtck/Ww4tevMh7xdY8shAgXCJvCo6W6wNg8X1ul8RRTv4nwyWSZjj9LdOJbw0jHRtznFZXqyECbpH2EXw3SqPoyeMkVjfp8z6o2C6vhllU4eNt9wc3yFuqKwKPJmlLmDNbzoMMK7/ZsSabQN2tL4ctuMhSAZUhBfnJEICZJStqr4Pt4Wk8WZji4wNgsY47iEBbgKSshwXvhh5oX410dHehTNvTkCnz9xOP+jOqNGLR6zEdlzHRBL4nWLzfbiSO+z9cpI0kU6Ha+5+RXqK67v0r5zKmzLGbyUubtSqXghp5NKsMWlo//BZ6KeYaHKdsf2JMrcUqH0ipf6NRxk=
